config/routes.rb
Faqbook31::Application.routes.draw do

  scope "/:locale" do
    devise_for :users

    namespace :admin do
      resources :settings
      resources :users
      resources :languages, :execpt => :show
    end

    resources :chapters do
      resources :questions
    end

    match 'admin' => 'admin/users#index'
  end
  
  match '/:locale' => 'home#index'
  root :to => 'home#index'

end

app/models/language.rb
class Language < ActiveRecord::Base
  validates_presence_of :name, :abbreviation
  
  def default?
    abbreviation == "en"
  end

  def self.current_name
    Language.find_by_abbreviation(I18n.locale.to_s).name
  end

end

app/controllers/admin/languages_controller.rb
class Admin::LanguagesController < ApplicationController
  before_filter :authenticate_user!
  authorize_resource
  # GET /languages
  # GET /languages.json
  def index
    @languages = Language.all
    add_breadcrumb t('breadcrumb.admin'), admin_path
    add_breadcrumb t('breadcrumb.languages'), ""

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @languages }
    end
  end

  # GET /languages/new
  # GET /languages/new.json
  def new
    @language = Language.new
    add_breadcrumb t('toc'), admin_path
    add_breadcrumb t('breadcrumb.languages'), admin_languages_path
    add_breadcrumb t('breadcrumb.new'), ""
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @language }
    end
  end

  # GET /languages/1/edit
  def edit
    @language = Language.find(params[:id])
    add_breadcrumb t('toc'), admin_path
    add_breadcrumb t('breadcrumb.languages'), admin_languages_path
    add_breadcrumb t('breadcrumb.edit'), ""
  end

  # POST /languages
  # POST /languages.json
  def create
    @language = Language.new(params[:language])
    add_breadcrumb t('toc'), admin_path
    add_breadcrumb t('breadcrumb.languages'), admin_languages_path
    add_breadcrumb t('breadcrumb.new'), ""
    respond_to do |format|
      if @language.save
        format.html { redirect_to admin_languages_url, notice: 'Language was successfully created.' }
        format.json { render json: @language, status: :created, location: @language }
      else
        format.html { render action: "new" }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /languages/1
  # PUT /languages/1.json
  def update
    @language = Language.find(params[:id])
    add_breadcrumb t('toc'), admin_path
    add_breadcrumb t('breadcrumb.languages'), admin_languages_path
    add_breadcrumb t('breadcrumb.edit'), ""
    respond_to do |format|
      if @language.update_attributes(params[:language])
        format.html { redirect_to admin_languages_url, notice: 'Language was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.json
  def destroy
    @language = Language.find(params[:id])

    respond_to do |format|
      if Language.count == 1
        format.html { redirect_to admin_languages_url, :alert => "You cannot delete the last language" }
        format.json { head :ko }
      elsif (@language.abbreviation == "en")
        format.html { redirect_to admin_languages_url, :alert => "You cannot delete the default language (English)" }
        format.json { head :ko }
      else
        @language.destroy
        format.html { redirect_to admin_languages_url, :notice => "Language deleted successfully" }
        format.json { head :ok }
      end
    end
  end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/admin/languages/_form.html.haml
= simple_form_for([:admin, @language], :html => {:class => "form-horizontal"}) do |f|
  
  = f.input :name
  = f.input :abbreviation
  
  .form-actions
    = f.submit nil, :class => "btn btn-primary"
    = link_to t('cancel'), admin_languages_path, :class => "btn"

app/views/admin/languages/edit.html.haml
.page-header
  %h1= t('.title')

= render 'form'

app/views/admin/languages/index.html.haml
.page-header
  %h1 
    = t('.title')
    = link_to_icon t('.new'), new_admin_language_path, "icon-file icon-white", :class => "btn btn-primary pull-right"
  

%table.table
  %thead
    %tr
      %th= t('.name')
      %th= t('.abbreviation')
      %th

  %tbody
    - @languages.each do |language|
      %tr
        %td= language.name
        %td= language.abbreviation
        %td
          - if !language.default?
            = link_to_icon t('actions.edit'), edit_admin_language_path(language), "icon-pencil icon-white", :class => "btn btn-mini btn-primary"
            = link_to_icon t('actions.delete'), admin_language_path(language), "icon-trash icon-white", :confirm => t('actions.delete_confirmation'), :method => :delete, :class => "btn btn-mini btn-danger"
          - else
            %em= t('.default_language')

app/views/admin/languages/new.html.haml
.page-header
  %h1= t('.title')

= render 'form'