config/routes.rb
Faqbook31::Application.routes.draw do

  scope "/:locale" do
    devise_for :users

    namespace :admin do
      resources :settings
      resources :users
      resources :languages, :execpt => :show
    end

    resources :chapters do
      resources :questions
    end

    match 'admin' => 'admin/users#index'
  end
  
  match '/:locale' => 'home#index'
  root :to => 'home#index'

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  has_many :questions, :order => "sequence", :dependent => :destroy
  acts_as_list :column => "sequence"
  translates :title, :description
  
  validates_uniqueness_of :title
  validates_presence_of :title, :sequence
  
  def self.sequence_select
    count = Chapter.count
    return [["First", 1]] if count == 0
    return [["First", 1], ["Last", 2]] if count == 1
    a = (2..count).to_a.map { |x| [x,x] } << ["Last", count + 1]
    a.insert(0, ["First", 1])
    a
  end
  
  def question_links
    links = []
    questions.each do |q|
      links << {:text =>"#{self.sequence}.#{q.sequence} #{q.title}", :anchor => q.anchor}
    end
    links
  end
  
  def last_update
    q = Question.where("chapter_id = #{self.id}").maximum('updated_at') || updated_at
    c = updated_at
    c > q ? c.strftime('%Y/%m/%d') : q.strftime('%Y/%m/%d')
  end
  
  def pdf_filename
    "#{sequence}-" + title.gsub(/\W+/, '-').chomp("-").downcase
  end
  
  def fully_translated?
    locale = I18n.locale
    questions.each do |q|
      return false if !q.translated_locales.include?(locale)
    end
    return true
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  include RedclothFormaters
  before_filter :authenticate_user!
  authorize_resource
  
  # GET /chapters
  # GET /chapters.json
  def index  
    add_breadcrumb t('toc'), chapters_path
    
    @chapters = Chapter.includes(:questions).order("chapters.sequence ASC")
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chapters }
      format.pdf {
        html = ""
        html += render_to_string(:layout => false , :action => "cover.html.haml")
        @chapters.each do |chapter|
          @chapter = chapter
          html += render_to_string(:layout => false , :action => "show.html.haml")
        end
        engine = Sass::Engine.for_file("#{Rails.root}/app/assets/stylesheets/pdf.css.scss", :syntax => :scss)
        css = pdf_css_image_path(engine.render)
        html = "<style>\n" + css + "\n</style>\n" + html
        kit = PDFKit.new(html)
        send_data(kit.to_pdf, :filename => "tdh-handbook", :type => 'application/pdf')
        return
      }
    end
  end
  
  def search
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
    @chapter = Chapter.includes(:questions).find(params[:id])
    @next = Chapter.find_by_sequence(@chapter.sequence + 1)
    @prev = Chapter.find_by_sequence(@chapter.sequence - 1)

    add_breadcrumb t('toc'), chapters_path
    add_breadcrumb @chapter.title, @chapter.question_links

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chapter }
      format.pdf {
        html = render_to_string(:layout => false , :action => "show.html.haml")
        engine = Sass::Engine.for_file("#{Rails.root}/app/assets/stylesheets/pdf.css.scss", :syntax => :scss)
        css = pdf_css_image_path(engine.render)
        html = "<style>\n" + css + "\n</style>\n" + html
        kit = PDFKit.new(html)
        send_data(kit.to_pdf, :filename => @chapter.pdf_filename, :type => 'application/pdf')
        return
      }
    end
  end

  # GET /chapters/new
  # GET /chapters/new.json
  def new
    if params[:locale] != "en"
      redirect_to chapters_url, :alert => "New content must be created English!"
      return
    end
    @chapter = Chapter.new
    add_breadcrumb t('toc'), chapters_path
    add_breadcrumb t('breadcrumb.chapters'), chapters_path
    add_breadcrumb t('breadcrumb.new'), ""
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chapter }
    end
  end

  # GET /chapters/1/edit
  def edit
    @chapter = Chapter.find(params[:id])
    add_breadcrumb t('toc'), chapters_path
    add_breadcrumb @chapter.title, chapter_path(@chapter)
    add_breadcrumb t('breadcrumb.edit'), ""
  end

  # POST /chapters
  # POST /chapters.json
  def create
    @chapter = Chapter.new(params[:chapter])
    add_breadcrumb t('toc'), chapters_path
    add_breadcrumb t('breadcrumb.chapters'), chapters_path
    add_breadcrumb t('breadcrumb.new'), ""
    
    respond_to do |format|
      if @chapter.save
        @chapter.insert_at(params[:chapter][:sequence].to_i)
        format.html { redirect_to @chapter, notice: 'Chapter was successfully created.' }
        format.json { render json: @chapter, status: :created, location: @chapter }
      else
        format.html { render action: "new" }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chapters/1
  # PUT /chapters/1.json
  def update
    @chapter = Chapter.find(params[:id])
    add_breadcrumb t('toc'), chapters_path
    add_breadcrumb @chapter.title, chapter_path(@chapter)
    add_breadcrumb t('breadcrumb.edit'), ""
    respond_to do |format|
      if @chapter.update_attributes(params[:chapter])
        @chapter.insert_at(params[:chapter][:sequence].to_i)
        format.html { redirect_to @chapter, notice: 'Chapter was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter = Chapter.find(params[:id])
    @chapter.remove_from_list
    @chapter.destroy

    respond_to do |format|
      format.html { redirect_to chapters_url }
      format.json { head :ok }
    end
  end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_form.html.haml
= simple_form_for(@chapter, :html => {:class => 'form-horizontal'}) do |f|

  = f.input :title, :input_html => {:class => "span5"}
  - sq_list = Chapter.sequence_select
  = f.input :sequence, :collection => sq_list, :include_blank => true, :selected => @chapter.sequence || sq_list.count, :input_html => {:class => "span5"}
  = f.input :description, :as => :text, :input_html => {:class => "span5"}
    
  .form-actions
    = f.submit nil, :class => 'btn btn-primary' 
    = link_to t('cancel'), @chapter ? @chapter : chapters_path, :class => 'btn'

app/views/chapters/_no_full_translation.html.haml
- if !@chapter.fully_translated?
  %div.alert.alert-info{:"data-dismiss" => "alert"}
    %button.close &times;
    = t('chapters.no_full_translation_html', :lang => Language.find_by_abbreviation(I18n.locale.to_s).name )

app/views/chapters/cover.html.haml
%div#cover Tdh Handbook
%div#last-update= "Last update on #{last_update}"

app/views/chapters/edit.html.haml
.page-header
  %h1= t('.title')

= render "shared/not_in_locale_info", :resource => @chapter
= render 'form'

app/views/chapters/index.html.haml
.page-header
  %h1
    = t('toc')
    - if user_signed_in? && current_user.admin?
      %div.btn-group.pull-right
        %a.btn.dropdown-toggle.btn-primary{"data-toggle" => "dropdown", "href" => "#"}
          = t('actions.action')
          %span.caret
        %ul.dropdown-menu    
          %li= link_to_icon t('actions.pdf'), chapters_path(:format => :pdf), "icon-print"
          %li.divider
          %li= link_to_icon t('actions.new_chapter'), new_chapter_path(:locale => "en"), "icon-file"
    - else
      = link_to_icon t('actions.pdf'), chapters_path(:format => :pdf), "icon-print icon-white", :class => "btn btn-warning pull-right"

%table.table.table-bordered.toc
  - @chapters.each do |c|
    %tr
      %th= link_to "#{c.sequence}. #{c.title}", c
    - c.questions.each do |q|
      %tr
        %td= link_to "#{c.sequence}.#{q.sequence} #{q.title}", chapter_path(c, :anchor => q.anchor)

app/views/chapters/new.html.haml
.page-header
  %h1= t('.title')

= render "shared/new_content_info"
= render 'form'

app/views/chapters/search.html.haml
%h1 Search Results

app/views/chapters/show.html.haml
.page-header
  %h1{:class => @chapters ? "page-break" : ""}
    = "#{@chapter.sequence}. #{@chapter.title}"
    - if params[:format] != "pdf"
      - if user_signed_in? && current_user.admin?
        %div.btn-group.pull-right
          %a.btn.dropdown-toggle.btn-primary{"data-toggle" => "dropdown", "href" => "#"}
            = t('actions.action')
            %span.caret
          %ul.dropdown-menu
            %li= link_to_icon t('actions.pdf'), chapter_path(@chapter, :format => :pdf), "icon-print"
            %li.divider
            %li= link_to_icon t('actions.edit'), edit_chapter_path(@chapter), "icon-pencil"
            %li= link_to_icon t('actions.new_question'), new_chapter_question_path(@chapter, :locale => :en), "icon-file"
            %li.divider
            %li= link_to_icon(t('actions.delete'), @chapter, "icon-trash", confirm: t('actions.delete_confirmation'), method: :delete)
      - else
        = link_to_icon t('actions.pdf'), chapter_path(@chapter, :format => :pdf), "icon-print icon-white", :class => "btn btn-warning pull-right"

= render "no_full_translation" if params[:format] != "pdf"

%div.description= @chapter.description

- @chapter.questions.each do |q|
  %div.anchor{:id => q.anchor}
  %div
    %h2.question
      = "#{@chapter.sequence}.#{q.sequence} #{q.title}"
      - if params[:format] != "pdf"
        - if user_signed_in? && current_user.admin?
          %div.btn-group.pull-right
            %a.btn.dropdown-toggle.btn-primary{"data-toggle" => "dropdown", "href" => "#"}
              = t('actions.action')
              %span.caret
            %ul.dropdown-menu    
              %li= link_to_icon t('actions.edit'), edit_chapter_question_path(@chapter, q), "icon-pencil"
              %li.divider
              %li= link_to_icon t('actions.delete'), [@chapter, q], "icon-trash", confirm: t('actions.delete_confirmation'), method: :delete
            
    %div.answer.well!= TextileQuestion.new(q, request.format.pdf?).to_html

%div.last-update= t('chapters.last_update', :update => @chapter.last_update)