config/routes.rb
Faqbook31::Application.routes.draw do

  scope "/:locale" do
    devise_for :users

    namespace :admin do
      resources :settings
      resources :users
      resources :languages, :execpt => :show
    end

    resources :chapters do
      resources :questions
    end

    match 'admin' => 'admin/users#index'
  end
  
  match '/:locale' => 'home#index'
  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base  
  ROLES = %w{super_admin reader}

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible  :email, :password, :password_confirmation, :remember_me, :role
  
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :password, :on => :create
  validates :password, :confirmation => true
  validates_presence_of :role
  
  def admin?
    role == "super_admin"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authenticate_user!
  authorize_resource
  
  def index
    @users = User.all
    add_breadcrumb t('breadcrumb.admin'), admin_path
    add_breadcrumb t('breadcrumb.users'), ""
  end
  
  def edit
    @user = User.find(params[:id])
    add_breadcrumb t('breadcrumb.admin'), admin_path
    add_breadcrumb t('breadcrumb.users'), admin_users_path
    add_breadcrumb t('breadcrumb.edit'), ""
  end
  
  def new
    @user = User.new
    add_breadcrumb t('breadcrumb.admin'), admin_path
    add_breadcrumb t('breadcrumb.users'), admin_users_path
    add_breadcrumb t('breadcrumb.new'), ""
  end
  
  def update
    @user = User.find(params[:id])
    add_breadcrumb t('breadcrumb.admin'), admin_path
    add_breadcrumb t('breadcrumb.users'), admin_users_path
    add_breadcrumb t('breadcrumb.edit'), ""
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to admin_users_url, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def create
    @user = User.new(params[:user])
    add_breadcrumb t('breadcrumb.admin'), admin_path
    add_breadcrumb t('breadcrumb.users'), admin_users_path
    add_breadcrumb t('breadcrumb.new'), ""
    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_url, notice: 'User was successfully created.' }
        format.json { render json: admin_users_url, status: :created, location: @chapter }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @user = User.find(params[:id])

    respond_to do |format|
      if User.count == 1
        format.html { redirect_to admin_users_url, alert: 'Cannot delete last user!'}
      else
        @user.destroy
        format.html { redirect_to admin_users_url, notice: 'User was successfully deleted.'}
        format.json { head :ok }
      end
    end
  end
end

app/views/admin/users/_form.html.haml
= simple_form_for([:admin, @user], :html => {:class => "form-horizontal"}) do |f|
  = f.input :email
  = f.input :role, :collection => User::ROLES.map{ |x| [x.humanize, x]}
  = f.input :password
  = f.input :password_confirmation
  
  .form-actions
    = f.submit nil, :class => "btn btn-primary"
    = link_to t('cancel'), admin_users_path, :class => "btn"

app/views/admin/users/edit.html.haml
.page-header
  %h1= t('.title')

= render 'form'

app/views/admin/users/index.html.haml
.page-header
  %h1
    = t('.title')
    = link_to_icon t('.new'), new_admin_user_path, "icon-user icon-white", :class => "btn btn-primary pull-right"

%table.table.table-striped
  %thead
    %tr
      %th= t('.email')
      %th= t('.role')
      %td &nbsp;
  %tbody
    - @users.each do |u|
      %tr
        %td= u.email
        %td= u.role.humanize
        %td
          = link_to_icon t('actions.edit'), edit_admin_user_path(u), "icon-pencil icon-white", :class => "btn btn-primary btn-mini"
          = link_to_icon t('actions.delete'), [:admin, u], "icon-trash icon-white", confirm: t('actions.delete_confirmation'), method: :delete, :class => "btn btn-danger btn-mini"

app/views/admin/users/new.html.haml
.page-header
  %h1= t('.title')

= render 'form'