config/routes.rb
Faqbook31::Application.routes.draw do

  scope "/:locale" do
    devise_for :users

    namespace :admin do
      resources :settings
      resources :users
      resources :languages, :execpt => :show
    end

    resources :chapters do
      resources :questions
    end

    match 'admin' => 'admin/users#index'
  end
  
  match '/:locale' => 'home#index'
  root :to => 'home#index'

end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Tdh Handbook
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  
    %script{:type => "text/javascript"}
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-2591396-5']);
      _gaq.push(['_trackPageview']);
      (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);})();
  
  %body
    %div.navbar.navbar-fixed-top
      %div.navbar-inner
        %div.container-fluid
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to t('app_title'), root_url, :class => "brand"
          %ul.nav.pull-right
            - if user_signed_in? && current_user.admin?
              %li.dropdown
                %a.dropdown-toggle{:href => "#", "data-toggle" => "dropdown"}
                  = t('admin_menu.title')
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to_icon t('admin_menu.users'), admin_users_path, "icon-user"
                  %li= link_to_icon t('admin_menu.languages'), admin_languages_path, "icon-globe"
                  %li= link_to_icon t('admin_menu.settings'), edit_admin_setting_path(Setting.first), "icon-wrench"
            %li.dropdown
              %a.dropdown-toggle{:href => "#", "data-toggle" => "dropdown"}
                %i.icon-globe.icon-white
                = Language.current_name
                %b.caret
              %ul.dropdown-menu
                - Language.all.each do |l|
                  %li= link_to l.name, locale: l.abbreviation unless I18n.locale == l.abbreviation.to_sym
            - if user_signed_in?
              %li= link_to_icon t('about'), "#help", "icon-question-sign icon-white", :"data-toggle" => "modal"
            %li= user_signed_in? ? link_to(t('logout'), destroy_user_session_path, confirm: t('actions.delete_confirmation'), :method => :delete) : link_to(t('login'), new_user_session_path)
          = render :partial => "shared/breadcrumb"

    %div.container
      %div
        %div.span8.offset2
          = render "shared/alerts"      
          = yield
    
    - if user_signed_in?
      = render :partial => "shared/help"